### ISSUE TITLE
Feature Request: History 

### ISSUE THREAD

**Issue by lightonflux** [FineFindus/eyedropper#1]
A history (automatic list with recently picket colours) is very important for users that need to pick several colours in sequence, e.g. to double-check if designs are in accordance with the colour palette of a project/company. Is such a feature planned? The Microsoft app that is listed as inspiration has such a feature. 

To improve on the Microsoft design: I suggest that not only a list of coloured shapes is displayed, but additionally the colour is displayed in hex representation on top of it or next to it.

**Comment by FineFindus** [comment]
Thanks for the feature request.

Yes, a history feature is definitely planned, although I'm not sure about the design of it (I'm not good at UI design), so I can't comment if it will have a hex representation or not.

**Comment by FineFindus** [comment]
A history feature has been added with 6329d4f06f47fc6ca9ab654b35ea84c402473703. If you don't want to wait for the next release, you can [download the latest nightly Flatpak from the CI action.](https://github.com/FineFindus/eyedropper/actions/runs/2985531470)
If you have any further feature request, feel free to open up another issue.
