### ISSUE TITLE
Show color screen by default, skipping placeholder view

### ISSUE THREAD

**Issue by EPadronU** [FineFindus/eyedropper#100]
**Is your feature request related to a problem? Please describe.**
Landing at this view on program startup is quire annoying since I find very useful introducing color codes for the palettes generation features provided by eyedropper
![image](https://github.com/FineFindus/eyedropper/assets/829947/589e3831-a544-4162-ab10-d8891d4f284d)

**Describe the solution you'd like**
An improved UX could be achieved by making the below view the default one
![image](https://github.com/FineFindus/eyedropper/assets/829947/6f59dd4d-ae18-4a1d-bdc9-75827588c382)

**Describe alternatives you've considered**
Provide a CLI flag for "jumping" directly to said preferred view on program startup

**Additional context**
Nothing to add.

**Information**
- OS: Debian 12
- Desktop Environment: KDE
- GTK-Theme/Adwaita-Style: Adwaita
- Version: 1.0.0 (Flatpak)

**Comment by FineFindus** [comment]
Thanks, but this has already been discussed in https://github.com/FineFindus/eyedropper/issues/25. Showing a default color by default has several drawbacks, such as confusing the user, not being able to easily remove the color, etc.
