### ISSUE TITLE
It's very difficult to use the palettes generated by eyedropper

### ISSUE THREAD

**Issue by EPadronU** [FineFindus/eyedropper#101]
**Is your feature request related to a problem? Please describe.**
When I click on any of the generated colors, the picked color gets changed to the one at the end of the corresponding row.

For example, clicking on any of the analogous colors on the below example, changes the picked color to the generated maroon
![image](https://github.com/FineFindus/eyedropper/assets/829947/6a3830a8-3080-4566-9cc1-7a2cf053e6c8)
![image](https://github.com/FineFindus/eyedropper/assets/829947/6166eaef-9745-461a-ace8-cf7945da1896)

**Describe the solution you'd like**
I'd like to be able to click on any of the colors and its hex code be copied to my clipboard.

**Describe alternatives you've considered**
The hex color could be shown inside a tooltip on mouse hover, a new eyedropper window could be opened with the selected color being set as the picker color. Anything that could make such a wonderful and useful feature (the palettes generation) actually usable.

**Additional context**
Nothing to add.

**Information**

- OS: Debian 12
- Desktop Environment: KDE
- GTK-Theme/Adwaita-Style: Adwaita
- Version: 1.0.0 (Flatpak)

**Comment by FineFindus** [comment]
Thanks for the feedback, I added tooltips in e881474842f657edcb2b923dc0d1f64329e20f23. I'm not sure about the other suggestions, I will have to think about them.
