### ISSUE TITLE
The picker cursor seems to have the wrong offsets

### ISSUE THREAD

**Issue by starccy** [FineFindus/eyedropper#107]
**Describe the bug**

The mouse cursor changes to the color picker icon after clicking the "Pick a Color" button.   

I expect the color selection to match the exact location of the icon, i.e. the lower left corner. But actually, it will select the color in the upper left corner.

**To Reproduce**

I created a picture containing four colors in different areas.

![color_test](https://github.com/FineFindus/eyedropper/assets/17541742/1ff8aaf5-bee2-478b-b466-8508ff45f897)

1. Click the "Pick a Color" button.
2. Move the cursor to the center.
3. Left-click the mouse and the **red** color will be selected.

**Expected behavior**

The **blue** color should be selected.

**Screenshots**

##### Before picking the color

![screenshot1](https://github.com/FineFindus/eyedropper/assets/17541742/7d5cc7f4-ff14-4c4c-8048-d24f6b30b6ae)

##### After picking the color (notice that the mouse cursor actually points to the red area)

![screenshot2](https://github.com/FineFindus/eyedropper/assets/17541742/254ae3a3-03ce-4c51-8724-9112ae67717a)

**Information**

- OS: Kali Linux 2023.4
- Desktop Environment: GNOME 45.0, X11
- GTK-Theme/Adwaita-Style: Adwaita, default
- Version: master branch(https://github.com/FineFindus/eyedropper/commit/b75e8a2e51da5b7cc07ff8abf4dee1b0cdbbd50c)

<details>
  <summary>Debugging Information</summary>

```
Eyedropper: 1.0.0-b75e8a2
Profile: Devel
Backend: X11
OS:
 - Name: "GNOME"
 - Version: "Nightly (Flatpak runtime)"
Libraries:
 - GTK: 4.13.3
 - Libadwaita: 1.5.0

Sandbox: Flatpak Info:
 - Name: com.github.finefindus.eyedropper.Devel
 - Runtime: runtime/org.gnome.Sdk/x86_64/master
 - Runtime commit: 99e70916dd03193cb9e043b5e9ca7363229a5c4d29106f2a58acceadecb66fcb
 - Arch: x86_64
 - Flatpak Version: 1.14.4
 - Devel: true


Portal error: None

```

</details>

**Comment by FineFindus** [comment]
Thanks for the report, but this is caused by the used custom cursor theme. When using the default adwaita cursors, it correctly shows and picks the red square.
![Color picker cursor picking a red square](https://github.com/FineFindus/eyedropper/assets/63370021/5ffc1695-69c8-4a8e-9d36-399762bdcfe3)
