### ISSUE TITLE
Color picker opening is too abrupt

### ISSUE THREAD

**Issue by marcinjahn** [FineFindus/eyedropper#11]
**Describe the bug**
When going through various windows of the app, it's smooth most of the time, in the sense that opening windows animate, they don't just appear out of nowhere. This is not the case with the color picker window (the one that appears after clicking "+"). You can see that in the *Screenshots* section (although it is a WEBM).

**To Reproduce**
See the WEBM

**Expected behavior**
I'd expect the window picker opening to be animated just like all the other windows.

**Screenshots**

[Kooha-2022-09-24-09-21-18.webm](https://user-images.githubusercontent.com/10273406/192085623-f6790d47-68cc-45a5-8a27-94cec809496f.webm)

You can see the difference between the first window popping up and the second one. The first one is animated, the second one is not.

**Information**

- OS: [Fedora 36
- Desktop Environment: Gnome 42
- GTK-Theme/Adwaita-Style: default
- Version: 0.3.1 (flathub)

**Comment by FeyXieXzf** [comment]
The color picker window does not belong to eyedropper, it belongs to gtk. Open an issue [there](https://gitlab.gnome.org/GNOME/gtk/-/issues).

**Comment by FeyXieXzf** [comment]
It's a long-existed bug.

**Comment by FineFindus** [comment]
Correct. Do you know if there is already an open issue on the GitLab page? Otherwise, I will open one.

**Comment by FineFindus** [comment]
Closing this for now, as I have created an [issue on the GTK issue tracker](https://gitlab.gnome.org/GNOME/gtk/-/issues/5214).
