### ISSUE TITLE
Not Working on SwayWM

### ISSUE THREAD

**Issue by Nydragon** [FineFindus/eyedropper#117]
**Describe the bug**
On Sway i get the notification "Failed to select a color" when trying to pick a  color.

**To Reproduce**

1. Click on "Pick a color"
2. Click anywhere on the screen 

**Expected behavior**
The color to be selected

**Additional context**
OS: Arch Linux x86_64
Kernel: 6.6.8-arch1-1
WM: sway
version: 1.0.0

Not sure if related but I am using the wlr screencast portal.

**Comment by FineFindus** [comment]
Thanks for the report. It's unlikely that the bug is on Eyedropper's side, since Eyedropper only uses the Screenshot Portal's color picker method. Please make sure your screenshot portal is set up correctly and working, if your portal is set up correctly and other color pickers using the portal work, please reopen this issue.

**Comment by Nydragon** [comment]
Alright, thank you very much for the info!

**Comment by azzamsa** [comment]
@Nydragon what is your final solution?

In Hyprland, it works fine, but it doesn't have the color previewer/magnifier when selecting a color.
It works fine in  GNOME though.

**Comment by Nydragon** [comment]
> @Nydragon what is your final solution?
> 
> In Hyprland, it works fine, but it doesn't have the color previewer/magnifier when selecting a color. It works fine in GNOME though.

I didn't find a solution for eyedropper (either wlr doesn't support that or I misunderstood how to configure) but i found this [alternative](https://www.reddit.com/r/swaywm/comments/ug5u86/comment/i6ypdt4/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
```
grim -g "$(slurp -p)" -t ppm - | convert - -format "%[pixel:p{0,0}]" txt:- | tail -n 1 | cut -d " " -f 4 | wl-copy
```
It will output the Hex value

**Comment by azzamsa** [comment]
It worked well for me in Hyprland

```conf
windowrulev2 = float,title:(Eyedropper)
windowrulev2 = center([1]) ,title:(Eyedropper)
```

![2024-01-13_09-05](https://github.com/FineFindus/eyedropper/assets/17734314/44455f80-6fe7-4d86-8bae-bcc773b36942)

**Comment by Nydragon** [comment]
Your message prompted me to test again, and by some magic it is working for me as well now...

This is my config; 

 ~/.config/xdg-desktop-portal/portals.conf
```ini
[preferred]
default=gtk
org.freedesktop.portal.ScreenCast=wlr
```

~/.config/xdg-desktop-portal-wlr/sway
```ini
[screencast]
chooser_type=simple
chooser_cmd=slurp -f %o -or
```

Make sure `$XDG_CURRENT_DESKTOP` is set to `sway`

(in case you are still looking @azzamsa)

I don't get a magnifying glass however, but I assume it can be changed in the second config file.
