### ISSUE TITLE
Hindi translation

### ISSUE THREAD

**Issue by Scrambled777** [FineFindus/eyedropper#125]
**Describe the bug**
Translated to Hindi on Weblate.
`translator-credits` is read only for me. 

**To Reproduce**

![image](https://github.com/FineFindus/eyedropper/assets/96682069/173ad8a4-f260-4f3c-b26d-65affe640083)

**Expected behavior**
It should be editable, as I can see details of other language translators.

**Screenshots**
Added above.

**Information**
Is anything else need to be done from my part. Cheers.

**Additional context**
None.

**Comment by FineFindus** [comment]
That's odd, it indeed should not be. Thanks for reporting it, should be fixed now.

**Comment by Scrambled777** [comment]
> That's odd, it indeed should not be. Thanks for reporting it, should be fixed now.

Thank you mate. Cheers.
