### ISSUE TITLE
launch app via shortcut

### ISSUE THREAD

**Issue by yotamguttman** [FineFindus/eyedropper#136]
it might already be possible and I've missed the option but I#d love being able to quickly launch the colour picker with a hotkey :)

**Comment by FineFindus** [comment]
I'm not quite sure what you mean by launching the color picker. Do you mean to start the application (which you can do via a [custom shortcut](https://docs.fedoraproject.org/en-US/quick-docs/gnome-setting-key-shortcut/)), or do you want to start the actual color picking process (which you can do via `CTRL-P`)?

**Comment by yotamguttman** [comment]
I could set a custom shortcut thanks for the tip!

it's definitely a good enough solution so we can close this issue here! but if you're interested to hear what I had in mind - it's a feature that comes with Microsoft Powertoys. you simply hit the hotkey and your cursor changes to as eyedropper first off. when you sample a colour anywhere on the screen, only then an interface, similar to Gnome Eyedropper one, pops up.

![image](https://github.com/FineFindus/eyedropper/assets/92977002/b5e7291c-e2fc-436c-afe6-0f07370a2b67)

what I also appreciated about the Powertoys version, is that it lets you choose from different shades of the colour you've just sampled. it helps in refining your choice right before you paste it into your graphic design programme. but it's definitely not a dealbreaker. this minor tweak can be done late :)
it was also nice to be able to quickly reference back to a previously sampled colours though.

**Comment by yotamguttman** [comment]
I could set a custom shortcut thanks. for the tip and the resource!

it's definitely a good enough solution so we can close this issue here!
but if you're interested to hear what I had in mind - it's a feature that comes with Microsoft Powertoys. you simply hit the hotkey and your cursor turns into as eyedropper tool. when you sample a colour anywhere on the screen, only then an interface, much like the Gnome Eyedropper one, pops up. it's definitely not a dealbreaker. the Gnome Eyedropper tool is far more powerful as is :)

**Comment by FineFindus** [comment]
Unfortunately, the application does not have the ability to capture hotkeys when not focused (see #19), it will be implemented as soon as possible.
