### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Scrambled777** [FineFindus/eyedropper#137]
**Describe the bug**
Icons of color formats are missing in `Preference > General > Color Formats`.

**To Reproduce**

1. Install from flathub on Fedroa 40 [KDE Spin]
2. Goto `Preference > General > Color Formats`.
3. Icons are missing by default.

**Expected behavior**
Icons should show.

**Screenshots**
![Screenshot_20240511_131357](https://github.com/FineFindus/eyedropper/assets/96682069/a2bcbd7d-68e1-4bf2-af8f-b2f05b1209f1)

**Information**

1. OS: Fedora 40 [KDE]
2. Installed from Flathub.
3. System & flatpak are fully updated.
4. App version `v 1.0.0`.

**Comment by FineFindus** [comment]
Thanks for the report. I guess `list-drag-handle-symbolic` is not included everywhere. Should be fixed now. Feel free to [test the nightly flatpak](https://github.com/FineFindus/eyedropper/actions/runs/9042374347/artifacts/1493414667) to see if it works correctly now (it uses a different ID, so it won't conflict with your existing installation).

**Comment by Scrambled777** [comment]
Hi there, thanks for the quick fix. 

I was not able to install from the above link due to some missing runtime, but I built the app with `Builder` and ran. The above missing icons are now displayed  properly.

But, now Header tab Button `General` & `Formats` are missing icons in test build.

See below screenshot
![Screenshot_20240511_165422](https://github.com/FineFindus/eyedropper/assets/96682069/f836a028-f17d-4888-8f89-97a2c9cdd2ae)

**Comment by FineFindus** [comment]
Should be fixed with 3041fa730529602ab2a24b853028da7599232de7
