### ISSUE TITLE
Option to Auto-Select "Pick a Color" when Launching the Application

### ISSUE THREAD

**Issue by jaspersn** [FineFindus/eyedropper#140]
**Is your feature request related to a problem? Please describe.**
I use a shortcut to launch the program, and wish there was a way for the application to automatically start choosing a color on startup, instead of having to choose "Pick a Color" every time.

**Describe the solution you'd like**
I would like an option to "Pick a new Color" when the application is launched, without the need to click the "Pick a Color" button first.

**Describe alternatives you've considered**
Having the option as an application preference under general or just have a launch option via CLI would be helpful. I can see it making more sense as a launch option, as this feature may become annoying when launching the app graphically.

**Additional context**
Allowing a custom shortcut for "Pick a new Color" may also help, as then I can "sync" it up with my shortcut for launching the app: ``Shift+Super+C``.

**Comment by FineFindus** [comment]
Thanks for the suggestion. There is already both a shortcut for picking a color (`CTRL+P`) and a temporary CLI option `--pick-color` which starts the color picking process immediately on application startup.

**Comment by jaspersn** [comment]
Thank you for the quick reply. I saw mention of the ``--pick-color`` launch option in another issue but it was not obvious to me it was implemented, my apologies. Im aware of the ``Ctrl+P`` shortcut, but was hoping for the ability to customize this shortcut.

**Comment by FineFindus** [comment]
> Im aware of the Ctrl+P shortcut, but was hoping for the ability to customize this shortcut.

GTK's default configuration is not set up for this. While it is possible to implement user-configurable shortcuts, I don't think it's worth implementing here, considering the increased code complexity and maintenance burden (the application already gets not enough :)).
