### ISSUE TITLE
Allow Color Input Without 

### ISSUE THREAD

**Issue by RageGamerBoi** [FineFindus/eyedropper#143]
**Is your feature request related to a problem? Please describe.**
Related to #72 but mostly a failure on my end (that I am currently unable to solve) as no Flatpak color pickers work on my system even with `xdg-desktop-portal-gnome` installed.
I use Budgie on Solus, and Door Knocker says only the Global Shortcuts portal is unavailable, with Screen Cast having some implementation issues.
Enough with that, it's a largely unrelated issue.

**Describe the solution you'd like**
Currently all I am able to do is see this and show an error popup:
![image](https://github.com/FineFindus/eyedropper/assets/105567407/10da7162-d0d5-4af3-9ac9-4d6ae57afb2e)
I would like to be able to just manually enter hex values, whether through GTK's color picker thing, or just a text box for a hex value, so I can use the other functions of this app, like palette creation.

**Describe alternatives you've considered**
I would obviously like to un-break color picker functionality on my end, but I believe this might be a good feature to have even if it isn't broken.

**Comment by FineFindus** [comment]
Thanks for the suggestion, as a workaround you can currently use `CTRL+R` to get a random color and then change its values. There's currently no other input method planned for the placeholder screen, this may change if there's a better design.
