### ISSUE TITLE
App doesn't work on nixos with kde or i3wm.

### ISSUE THREAD

**Issue by Chlebqowy** [FineFindus/eyedropper#152]
**Describe the bug**
App doesn't work at all in nixos with plasma5 or i3wm.

**To Reproduce**

1. Run the app
2. Click pick a color

**Expected behavior**
The color picking tool working
**Screenshots**
![Screenshot_20240724_172453](https://github.com/user-attachments/assets/b81d49f5-42d0-48d5-9971-a34db72e0dd3)

**Information**

I can't get any debugging information

**Additional context**
I get this error 

ERROR eyedropper::window > ZBus Error: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop

Here is my neofetch in case something that is shown by it affects the app.
![Screenshot_20240724_172735](https://github.com/user-attachments/assets/43068da0-2db2-4701-a1f9-f4f575c88a63)

**Comment by FineFindus** [comment]
The issue is that your system is not properly configured for color picking. Eyedropper uses the `PickColor` method of the `org.freedesktop.portal.Screenshot` portal interface.
