### ISSUE TITLE
Change the color picker cursor

### ISSUE THREAD

**Issue by davidkisvari** [FineFindus/eyedropper#159]
The current color picker cursor is too large and it is not clear what you are pointing at if you want to have the color of a smaller object with finer details. Image trying to get the color of some text. By pointing at it, you have a much higher chance of getting the background color instead as you don't know exactly which part of the cursor is picking up the color. By using a regular pointy cursor this wouldn't be an issue.

**Comment by FineFindus** [comment]
Please include an image of the color picker cursor.

**Comment by davidkisvari** [comment]
Sorry it was my mistake, although I'm using Adwaita cursors I had a different icon theme and I didn't know the the color picker's cursor is actually an icon, this was the issue. Thanks!
