### ISSUE TITLE
html rgba format support (or custom patterns)

### ISSUE THREAD

**Issue by gumby0q** [FineFindus/eyedropper#161]
Hi,
previously there was a bug or feature to adjust template of the color so I used the app with modified rgb value to rgba format

html rgba format example is `rgba(255, 99, 71, 1)`
https://www.w3schools.com/html/html_colors_rgb.asp

But now after recent updates there is only hardcoded predefined styles 

no matter that app will set the alpha value to 1 - it will be just any way more convenient

**Comment by gumby0q** [comment]
oh i dug some code and have found new config in formating section of preferences

![image](https://github.com/user-attachments/assets/50045ea3-633e-48fe-b388-676b602815c6)

 that sets the rgb to rgba format

but it works with a bug -> it sets the 255 instead of 1 :)
![image](https://github.com/user-attachments/assets/3f9e7caf-a596-4372-8af5-b5e39687c33a)

so I assume the problem starts somewhere here:
https://github.com/FineFindus/eyedropper/blob/bb3e50bdd27debf00f9cfc2552645755cd56de9d/src/colors/notation.rs#L102C21-L102C24

so it should be replaced with 
https://github.com/FineFindus/eyedropper/blob/bb3e50bdd27debf00f9cfc2552645755cd56de9d/src/colors/notation.rs#L122C1-L122C52

**Comment by FineFindus** [comment]
Custom formats were removed as I found them difficult to maintain and integrate into the app.

> but it works with a bug -> it sets the 255 instead of 1 :)

I guess I must have just overlooked that when implementing it :)

![image](https://github.com/user-attachments/assets/326814d0-41d0-4b43-a701-3ae1dec62a63)
