### ISSUE TITLE
UI: CIE illuminants dropdown does not fit it's content

### ISSUE THREAD

**Issue by libreajans** [FineFindus/eyedropper#22]
Hi, the new CIE illuminants list does not fit it's content properly. It's not showing longer strings.

**To Reproduce**

1. Open Eyedropper.
2. Go to Preferences
3. Try to select something from "CIE standard observer"

**Screenshots**
![eaeae](https://user-images.githubusercontent.com/6218679/196005989-9edcc4b8-ed33-4420-b13f-a627992f26a7.png)
(Icons not important) 

**Information**

- OS: Ubuntu 22.04.1
- Desktop Environment: Gnome 42
- Icon Theme: Breeze theme from KDE desktop
- GTK-Theme/Adwaita-Style: Adwaita
- Eyedropper Version: From master branch (commit: ec993e149c5f1acc4312962f6ba736b75504b2f4)

The line of strings: https://github.com/FineFindus/eyedropper/blob/master/data/resources/ui/preferences.ui#L50-L69

**Comment by libreajans** [comment]
I think it was related to GTK4 but I couldn't find enough information.

**Comment by FineFindus** [comment]
Thanks for the report, I'm aware of it. Since the UI is built using AdwPreference widgets, this is probably an upstream bug. I will be trying to fix this or open an issue on the libadwaita repo.

Also, the missing icons are a result from the custom icon theme, it seems like most icon themes do not include the `list-drag-handle-symbolic` icons.

**Comment by FineFindus** [comment]
I've opened a bug report on the [libadwaita GitLab](https://gitlab.gnome.org/GNOME/libadwaita/-/issues/582).

I'm closing this for now, since there is nothing else I can do right now. If I find a solution for it, or the bug gets fixed, I will reopen this.

**Comment by FineFindus** [comment]
Never mind, I fix it.

![Image](https://user-images.githubusercontent.com/63370021/197332939-8b1fde34-a38a-47d6-968d-34964f41a0bb.png)
It's a bit hacky, does not always look the prettiest, since it changes its width when the selected item is changed, but I think that is acceptable.
