### ISSUE TITLE
Distribute as AppImage

### ISSUE THREAD

**Issue by mcmxcdev** [FineFindus/eyedropper#3]
**Is your feature request related to a problem? Please describe.**

Currently I am using the AUR package and upgrading takes forever due to the compilation step. It also requires rust and ninja to be installed locally, which I otherwise not need and they take up a lot of space.

**Describe the solution you'd like**
It would be great if eyedropper would be offered as AppImage install, since that is much more consumer friendly.

**Describe alternatives you've considered**
Stick to AUR

**Information**

- OS: Manjaro Linux
- Desktop Environment: Gnome 42
- GTK-Theme/Adwaita-Style: Adwaita
- Version: [e.g. 0.1.0] 0.1.0

**Comment by FineFindus** [comment]
Thanks for the suggestion, I will have to think about this.

If you don't want to use the AUR, you could also use the [flatpak from flathub.org](https://flathub.org/apps/details/com.github.finefindus.eyedropper), which has been officially released a few days ago (I just haven't updated the README yet).

**Comment by mcmxcdev** [comment]
I will think about switching to Flatpak then, thanks!

**Comment by docop** [comment]
Hi the soft look a very nice tool and can be quite usefull. Can it be possible to have it in appimage.
 flatpk stuff is all to download and so on.. Developping don't need internet what so ever. Just plug the usb key and we code. So having this as a true portable app, in appimage, could be quite handy.
thanks

**Comment by FineFindus** [comment]
I will be looking into this a bit more, but I can't promise anything, as it is currently not on my priority list. 

If someone has more experience working with AppImage and would be willing to create a release action for it, similar to the [flatpak one](https://github.com/FineFindus/eyedropper/blob/master/.github/workflows/cd.yml), I would gladly merge their pull request.
But for now, I think it's better for me to spend me time implementing new features, since flatpak should cover most use case.

**Comment by dylhack** [comment]
While on Fedora I have the issue of #28, I think an appimage would be a great substitute.

**Comment by dylhack** [comment]
It is the same issue

```
Linux 6.1.10-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC x86_64 x86_64 x86_64 GNU/Linux
ERROR eyedropper::window > Portal request didn't succeed: Other
```

**Comment by FineFindus** [comment]
I'm assuming you're also using a window manager?

**Comment by dylhack** [comment]
Yes I'm on the Cinnamon spin (muffin in this case)

**Comment by FineFindus** [comment]
If memory serves me correctly, cinnamon is still using X11, so #28 doesn't apply (it's about the portal not working on wlroots). The app should work on X11. Please create a new issue, thanks in advance!

**Comment by FineFindus** [comment]
Closing this, as I have no desire to implement it.
