### ISSUE TITLE
Missing icons in GNOME Builder

### ISSUE THREAD

**Issue by rene-coty** [FineFindus/eyedropper#31]
Compiling the latest code in GNOME Builder (on Fedora 37 / GNOME 43) I noticed that some icons were missing in the Preferences Window (see screenshot below).
![Capture d’écran du 2022-12-17 14-12-39-min](https://user-images.githubusercontent.com/95506494/208243774-fa44d03e-4e48-469e-b8c8-0405f87099b2.png)
(Previously all the icons of the 'General' tab were missing, but it seems to be ok now)

**Comment by FineFindus** [comment]
I changed the icon in 0cb8065174d6290acbf3dfc42e4e5703a0f03c6a, could you check if it's now fixed?

**Comment by rene-coty** [comment]
Yep it's fine now :)

**Comment by FineFindus** [comment]
Great!
