### ISSUE TITLE
Removed duplicates from history

### ISSUE THREAD

**Issue by lightonflux** [FineFindus/eyedropper#34]
Imagine you select a sequence of colours. And by accident or without knowledge you pick a colour twice or thrice, which easily happens when colours are very similar. 

To illustrate the problem with duplicates in the history:

![Bildschirmfoto vom 2022-12-26 20-22-47](https://user-images.githubusercontent.com/1377943/209578140-e9814c6e-d053-40c9-a678-1f98b32b72ec.png)

The green and red in the history are listed twice, but are the exact same values. 

I think that only keeping the most recent occurrence of the colour in the history would be a good idea. But I am not 100% sure. Some people might use the order of the history to remember the context where they took the colour. 

Maybe some other users of the software could chime in.

**Comment by lightonflux** [comment]
Of course, the colour should not be silently removed from history, displaying a toast notification might be a good option to inform the user.

**Comment by FineFindus** [comment]
Thanks, for the suggestion, I will have to think about this. I understand the issue that it is confusing to have the same color multiple times in the history, but I think it might be more confusing if the color gets removed.
I dislike the idea of a toast notification, I think it would add too much unnecessary clutter and distract from more important parts of the UI.

**Comment by FineFindus** [comment]
Implemented in [`a636292ba049a6460a7e231c3f9d134890c3a71c`](https://github.com/FineFindus/eyedropper/commit/a636292ba049a6460a7e231c3f9d134890c3a71c).

I'm not super happy with either behavior, so I will adjust it based on future user feedback.
