### ISSUE TITLE
Add labels to history buttons

### ISSUE THREAD

**Issue by lightonflux** [FineFindus/eyedropper#35]
If you are taking a many colours that are similar but different, it might be hard to (re)find the correct colour within the history.

Adding labels (#hex representation) would help "power" users to refind a colour from history with fewer clicks. 

![Bildschirmfoto vom 2022-12-26 20-25-46](https://user-images.githubusercontent.com/1377943/209578506-68ee3805-21b1-46fd-a714-dc6c52feafef.png)

Because this feature would only help power users and increase the size of the history (in the GUI) quite a lot, it would be best to make this optional. Or enable it automatically, if the app detects that colours are too close to each other.

**Comment by lightonflux** [comment]
Another option to enable this feature could be based on the window width.

**Comment by FineFindus** [comment]
Thanks, for the suggestions, this has already been added, in the newest unreleased version, it will show a tooltip (the hex color) when hovering over the color. The new version should hopefully be released soon, I'm only waiting for some translations.
