### ISSUE TITLE
Add complete translation support

### ISSUE THREAD

**Issue by rene-coty** [FineFindus/eyedropper#4]
I would like to start translating the app (in French), but currently the translation support is not very comprehensive. There is a po folder but as long as there is no .pot file inside, translators will not be able to translate all the UI (e.g.: for now I can't translate the strings of the Preference window, nor the metainfo / app description etc.)...

**Comment by FineFindus** [comment]
Thank you for your offer to translate the app. I am aware that there is currently no support for adding translations, I just haven't gotten around to adding it and was more focused on adding new functionality. 

 Support for adding translations will be added in the coming days, hopefully on this weekend.

**Comment by FineFindus** [comment]
A [`.pot`](https://github.com/FineFindus/eyedropper/blob/e7755912dcb71c521873dabab8d6612893bc0a96/po/Eyedropper.pot) file has been added in the latest commit.

Good luck with translation.
