### ISSUE TITLE
Add the option to alter how many tiles for each category when generating a palette 

### ISSUE THREAD

**Issue by LucasGGamerM** [FineFindus/eyedropper#41]
I have been trying to have more tint options, so that i can use it to create more palettes for my android app.

**Comment by FineFindus** [comment]
Implemented. This setting is not exposed to the user, as it will break the UI and not work correctly with large values.

![Palette dialog with broken shades/tints generation](https://user-images.githubusercontent.com/63370021/224164899-c80f7c2b-bd74-46f5-8432-c7248f099559.png)
