### ISSUE TITLE
bug: Border to the right

### ISSUE THREAD

**Issue by sophie-h** [FineFindus/eyedropper#42]
BTW: The template titles are swapped.

![Screenshot from 2023-02-21 01-23-08](https://user-images.githubusercontent.com/3466497/220217531-0fd50b36-c026-457f-ad2d-a6756aa9df56.png)

Hard to see with a white background but there is a border to the right. Probably from the hidden color list.

**Comment by FineFindus** [comment]
Good catch, I think it should be fixed now!
![](https://user-images.githubusercontent.com/63370021/220372912-7ec489b2-4fe5-4ff5-84fa-01b2e8a2017a.png)
