### ISSUE TITLE
Also list latest color on the right side?

### ISSUE THREAD

**Issue by sophie-h** [FineFindus/eyedropper#43]
I repeatedly got confused by the latest color not being listed on the right side.

Would be fine for me to hide the list on the right until there are two colors.

But removing the current color especially got confusing when selecting it from the list and then it disappears. That's usually not how lists of things work in GNOME.

@bertob you have an opinion?

**Comment by bertob** [comment]
Yeah, I was wondering about this as well, it feels counterintuitive to me that the current color isn't there. Adding it and special casing the single color case makes sense to me :+1:

**Comment by FineFindus** [comment]
I'm a bit confused, does the latest color mean the one that's currently selected/picked/ displayed in the main window?
If I understand it correctly, it should also be shown in the history (but only if there are already at least one color) and not be removed/moved up when it's reselected?

**Comment by sophie-h** [comment]
> I'm a bit confused, does the latest color mean the one that's currently selected/picked/ displayed in the main window?

Yes

> it should also be shown in the history (but only if there are already at least one color)

Yes :)

> not be removed/moved up when it's reselected?

Yes. I don't have a too strong opinion about moving it up or not though.

**Comment by FineFindus** [comment]
Fixed it, it will now display the current color in the history as well, if there is already one.

![Eyedropper with current color in the list](https://user-images.githubusercontent.com/63370021/220758679-cf3c3541-329b-4359-bdf1-f7fb30fe7c44.png)
