### ISSUE TITLE
Ctrl+W should close the current window

### ISSUE THREAD

**Issue by sophie-h** [FineFindus/eyedropper#47]
https://developer.gnome.org/hig/reference/keyboard.html

**Comment by FineFindus** [comment]
I might be missing something, but I think this is already the case? `Ctrl+W` always worked and `Ctrl+Q` was added in bc613eaae5495b0506a17544cebbbf1db501469d.

**Comment by sophie-h** [comment]
sorry, totally works. maybe I was hitting the wrong key
