### ISSUE TITLE
Allow to undo "Clear History"

### ISSUE THREAD

**Issue by sophie-h** [FineFindus/eyedropper#48]
Not that important I guess. But in theory, it should be undoable per HIG.

**Comment by FineFindus** [comment]
Closed in 1b954a428ece28b3924cdb22b20e64c0a6a3dc40. A toast is now shown with an `Undo` button.

![Undo Toast](https://user-images.githubusercontent.com/63370021/220434172-ca230f5b-6655-40e2-b3ef-e35ccd218441.png)
