### ISSUE TITLE
Define custom color (key-colors) in metadata

### ISSUE THREAD

**Issue by sophie-h** [FineFindus/eyedropper#49]
Not sure how it will turn out with the new app icon but maybe specify a manual color

https://gitlab.gnome.org/GNOME/gnome-software/-/wikis/Software-metadata#user-content-how-to-set-the-carousel-tile-background-colour

https://apps.gnome.org/app/com.github.finefindus.eyedropper/

**Comment by FineFindus** [comment]
|   Before                                                                                                                    	|                                                                                                                      	|                                                                                                                      	|
|-----------------------------------------------------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------	|
| ![Brown color](https://user-images.githubusercontent.com/63370021/220359230-84f88084-415e-46f9-bf34-1c89ef987219.png) 	| ![Pink color](https://user-images.githubusercontent.com/63370021/220359254-4112fd15-e8fc-436a-8ddc-9fd72c3377ee.png) 	| ![Blue color](https://user-images.githubusercontent.com/63370021/220359242-1652cb8f-473f-4ca6-ad42-0f71801a43d3.png) 	|

| After                                                                                                                     	|                                                                                                                       	|
|----------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------	|
| ![Blue color](https://user-images.githubusercontent.com/63370021/220359242-1652cb8f-473f-4ca6-ad42-0f71801a43d3.png) 	| ![Green color](https://user-images.githubusercontent.com/63370021/220359245-bb8eea28-b946-4717-8a84-96fc9d89a47b.png) 	|

I swapped the generated colors for a green and a blue one, although in my testing GNOME software seemed to prefer the blue one and never showed the green color.
