### ISSUE TITLE
[AUR] "Failed to Pick a Color" 

### ISSUE THREAD

**Issue by AlbusPercivalDumbledore** [FineFindus/eyedropper#56]
Similar to #6 and #16, but 
1. I've installed from AUR (eyedropper package)
2. Happens on a DE (Cinnamon)

OS: EndeavourOS Linux x86_64
DE: Cinnamon
Version: eyedropper 0.6.0-1

![1](https://user-images.githubusercontent.com/82368617/221891494-f8205d46-54b3-49ce-91fc-569af7ec7c66.png)

Not sure if this should be reported here, since its an unofficial package. Please feel free to close it.

**Comment by FineFindus** [comment]
As this issue occurred in a third party project, please test if it persists when using the flatpak version. Please also include the debug information (`About Eyedropper` ⇒ `Troubleshooting` ⇒ `Debugging Information`)

**Comment by AlbusPercivalDumbledore** [comment]
As in screenshot I've linked, there's no Hamburger menu, so I'm unable to retrieve Debug Information. Unfortunately I can't install from Flatpak due to space constraints.

However, I cross-checked by installing eyedropper-git package from AUR, and it came up with following error on command line: 

![2](https://user-images.githubusercontent.com/82368617/222028573-8d837ad4-ac1b-473b-ad61-9678e22e923e.png)

So I installed xdg-desktop-portal and xdg-desktop portal-gnome:

![3](https://user-images.githubusercontent.com/82368617/222028872-8458f05d-f086-4510-8b1c-81a95b70607b.png)

Now, after a Restart, it shows following error:

![4](https://user-images.githubusercontent.com/82368617/222031694-c6e3d12a-aea0-48a0-a02e-a5c1748273d1.png)

Is there any other information I can provide, that might be useful?

**Comment by AlbusPercivalDumbledore** [comment]
Output of 
`/usr/lib/xdg-desktop-portal --replace --verbose`

```
XDP: load portals from /usr/share/xdg-desktop-portal/portals

(/usr/lib/xdg-desktop-portal:41789): xdg-desktop-portal-WARNING **: 08:26:33.137: Failed to create background monitor: Failed to own background monitor D-Bus name

(/usr/lib/xdg-desktop-portal:41789): xdg-desktop-portal-WARNING **: 08:26:33.138: No skeleton to export
XDP: Falling back to gnome.portal for org.freedesktop.impl.portal.Wallpaper
XDP: providing portal org.freedesktop.portal.Wallpaper
XDP: Falling back to gnome.portal for org.freedesktop.impl.portal.Account
XDP: using org.freedesktop.impl.portal.Account at org.freedesktop.impl.portal.desktop.gnome

XDP: providing portal org.freedesktop.portal.Account
XDP: Falling back to gtk.portal for org.freedesktop.impl.portal.Email
XDP: providing portal org.freedesktop.portal.Email
XDP: Falling back to gnome-keyring.portal for org.freedesktop.impl.portal.Secret
XDP: providing portal org.freedesktop.portal.Secret
XDP: Falling back to gnome.portal for org.freedesktop.impl.portal.DynamicLauncher
XDP: providing portal org.freedesktop.portal.DynamicLauncher
XDP: Falling back to gnome.portal for org.freedesktop.impl.portal.ScreenCast
XDP: providing portal org.freedesktop.portal.ScreenCast
XDP: Falling back to gnome.portal for org.freedesktop.impl.portal.RemoteDesktop
XDP: providing portal org.freedesktop.portal.RemoteDesktop
XDP: org.freedesktop.portal.Desktop acquired

```

Found a similar issue here: https://github.com/flatpak/xdg-desktop-portal/issues/861

**Comment by FineFindus** [comment]
Sorry for the long silence, I'm currently relatively busy, so I'll try to fix this issue over the coming weeks.

> As in screenshot I've linked, there's no Hamburger menu, so I'm unable to retrieve Debug Information. 

Interesting, I see. How do you even use the app without the header bar? Without it, it's missing most of its features…

> However, I cross-checked by installing eyedropper-git package from AUR, and it came up with following error on command line:

While I appreciate the effort, there hasn't been any changes to the picker system between the latest release and the head, so starting the app with `RUST_LOG=eyedropper=debug` would've achieved the same result.

> Is there any other information I can provide, that might be useful?

Would it be possible for you to test if it works on GNOME? I have the feeling, that it might be related to the portal implementation. Also, I noticed, that in your output of ` /usr/lib/xdg-desktop-portal --replace --verbose` the Screenshot portal is missing.  I will try to recreate the issue in cinnamon, but I can't promise much.

**Comment by FineFindus** [comment]
I refactored the color picking code in d979289c5a4169d68de7e43305b75eed41c35c50, could you please recompile and test if the issue still persists?

**Comment by FineFindus** [comment]
Sure, no problem. It might also be worthwhile testing if other color picking apps work, for example [Contrast](https://gitlab.gnome.org/World/design/contrast), if not, it would be an issue related to the portal implementation, which I can do nothing about.

**Comment by MrPancakes39** [comment]
> testing if other color picking apps work, for example [Contrast](https://gitlab.gnome.org/World/design/contrast)

For me same error:
```
Mar 09 10:27:09.322 ERROR contrast::colour_entry: Failed to pick a color Portal request didn't succeed: Other
```

**Comment by FineFindus** [comment]
> > testing if other color picking apps work, for example [Contrast](https://gitlab.gnome.org/World/design/contrast)
> 
> For me same error:
> 
> ```
> Mar 09 10:27:09.322 ERROR contrast::colour_entry: Failed to pick a color Portal request didn't succeed: Other
> ```

In that case, this is an error with the portal implementation of the desktop environment/ window manager. Please open an issue there.
