### ISSUE TITLE
Flatpark or AUR version "Failed to pick a color" error when try to pick a color

### ISSUE THREAD

**Issue by pierre-rs** [FineFindus/eyedropper#72]
**Describe the bug**
Application starts but when trying to select a color it shows an error.

**To Reproduce**

1. Start the app
2. Click the "Pick a color" button
3. See error "Failed to pick a color".

**Expected behavior**
Click the "Pick a color" button and select a color.

**Screenshots**
![Screenshot from 2023-06-27 13-34-38](https://github.com/FineFindus/eyedropper/assets/57575719/49dd1c67-9c4a-4dda-a333-f0a5eeaa21d2)

**Information**

- OS: Arcolinux
- Desktop Environment:  Gnome 44.2
- GTK-Theme/Adwaita-Style: Adwaita, Dark
- Version: 0.6.0

<details>

```
```

</details>

**Additional context**
> Example: Start app from terminal
```
flatpak run com.github.finefindus.eyedropper
```
```
ERROR eyedropper::window > Portal request failed: org.freedesktop.zbus.Error: No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop`
```
> App installed from Flathub

**Comment by FineFindus** [comment]
The Screenshot portal which is for picking colors is not available. Please ensure that it is installed and used, it's most likely named `xdg-desktop-portal-gnome`.

**Comment by pierre-rs** [comment]
Thanks! Installing `xdg-desktop-portal-gnome`  ( `sudo pacman -S xdg-desktop-portal-gnome` ) solved the problem.

**Comment by zehkira** [comment]
> The Screenshot portal which is used for picking colors is not available. Please ensure that it is installed and used, it's most likely named `xdg-desktop-portal-gnome`.

What about non-GNOME desktop environments that use `xdg-desktop-portal-gtk` instead? I'm testing this on Cinnamon on the latest LMDE and getting the "failed to pick color" error.

```sh
zee@vm:~$ flatpak run com.github.finefindus.eyedropper
libEGL warning: DRI2: failed to authenticate
 ERROR eyedropper::window > Portal request didn't succeed: Other
```
