### ISSUE TITLE
Adobe Color style image-to-color picking utility

### ISSUE THREAD

**Issue by dacwatson** [FineFindus/eyedropper#78]
**Describe the solution you'd like**
It would be extremely useful to have the ability to extract, automatically or manually, a color palette from an image.

Upon launching eyedropper, the user might be able to  which allowed the user to either paste in their image or otherwise select it in some way. Upon choosing an image, the user would be prompted with some selection tools and the corresponding palette below. 

Would you be on board with having this sort of functionality within the app? I was thinking about trying to implement it. Let me know.

**Additional context**

[Adobe Color](https://color.adobe.com/create/image)
![image](https://github.com/FineFindus/eyedropper/assets/70728355/649a8c34-321b-411c-8455-86267a5f9b4d)
![image](https://github.com/FineFindus/eyedropper/assets/70728355/efc09508-4eb1-4d31-a571-bc04dcf743c5)

**Comment by FineFindus** [comment]
Thanks for the suggestion. This app is more about converting between different color formats than picking colors, so I'm not sure if this really fits in with the scope of the project. The feature probably fits better to [paleta](https://github.com/nate-xyz/paleta), an app for generating palettes from an image.
