### ISSUE TITLE
Magnifying glass effect on cursor

### ISSUE THREAD

**Issue by n1c0saurio** [FineFindus/eyedropper#79]
Would be really useful if the cursor had a zoomed preview of the area where you want to pick the color, like Firefox eyedropper.

This is how look Firefox eyedropper:
![imagen](https://github.com/FineFindus/eyedropper/assets/16579247/18ef5ae7-7932-4ca1-9c74-a8fa5e4a53a6)

**Information**
- OS: Fedora Workstation 38
- Desktop Environment: Gnome 44
- GTK-Theme/Adwaita-Style: Adwaita
- Version: 0.6.0

**Comment by FineFindus** [comment]
Sorry for the late response. Thanks for the suggestion. I would love to implement something like this. Sadly, I don't think that is possible. Currently, the app calls the portal to get a color. Implementing a magnifier would probably require deeper integration than just using portals. If someone has a few pointers on how to implement this, I'm happy to take a look again, closing for now.

**Comment by salim-b** [comment]
The relevant upstream feature request is here: [**#6219: Add magnifier to color picker**](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6219)
