### ISSUE TITLE
Crash after picking a color

### ISSUE THREAD

**Issue by kra-mo** [FineFindus/eyedropper#82]
**Describe the bug**
The application crashes after picking a color

**To Reproduce**

1. Pick a color

**Screenshots**

https://github.com/FineFindus/eyedropper/assets/93832451/67096680-e0da-4241-8bc8-aedd459280b7

**Information**

- OS: Fedora 39
- Desktop Environment: GNOME 45
- GTK-Theme/Adwaita-Style: Adwaita
- Version: git master

<details>
  <summary>Debugging Information</summary>

The dialog isn't accessible without picking a color :p

</details>

**Comment by FineFindus** [comment]
This has been known for a while and has a temporary fix applied in https://github.com/FineFindus/eyedropper/commit/a1a78bb81a91b4564734a19d47e70e538b9e47ba.
