### ISSUE TITLE
Allow deleting individual colors from history

### ISSUE THREAD

**Issue by bertob** [FineFindus/eyedropper#93]
It'd be nice to have some way to remove colors from the history, maybe we could have a context menu on the color dots on the right?

**Comment by FineFindus** [comment]
I agree, this may also help with https://github.com/FineFindus/eyedropper/issues/57, but I'm not sure how the user would open the context menu. Adding a menu button next to the color feels a bit _too_ much, as it would only be used to remove a color from the history.

**Comment by bertob** [comment]
Right-click / long press should work, no?

**Comment by FineFindus** [comment]
Of course, but the [GNOME HIG](https://developer.gnome.org/hig/guidelines/pointer-touch.html) discourages the use of secondary actions with alternative actions.
