### ISSUE TITLE
Option to save palette not visible / clear to user

### ISSUE THREAD

**Issue by dieub56** [FineFindus/eyedropper#97]
**Describe the bug**
Can't find the option to save color palettes for later use, or at least not as shown in the app screenshots on [Gnome Apps](https://apps.gnome.org/Eyedropper/)

**Screenshots**
![image](https://github.com/FineFindus/eyedropper/assets/47575489/55f3c2e1-17f8-4108-b528-1c1575943689)
![image](https://github.com/FineFindus/eyedropper/assets/47575489/da2a959e-3cce-45db-a1ea-78005740a741)

**Information**
- OS: Fedora 39
- Desktop Environment: Gnome 45
- GTK-Theme/Adwaita-Style: Custom Theme
- Version: 1.0.0

**Additional context**
Installed using flatpak

**Comment by FineFindus** [comment]
You can click on the color button in the main interface to open the palette dialog.
